### ISSUE TITLE
invalid number of breaks

### ISSUE THREAD

**Issue by rspfau** [DevonDeRaad/SNPfiltR#1]
I'm using SNPfiltR for the first time to filter the final.recode.vcf file from dDocent. 

Upon executing hard_filter(vcfR=vcfR), it throws the following error:
Error in hist.default(gq.matrix, xlab = "genotype quality") : 
invalid number of 'breaks'

Upon executing vcfR<-filter_allele_balance(vcfR):
Error in hist.default(al.bal, xlim = c(0, 1), ylab = "number of genotypes", : 
invalid number of 'breaks'
[R Notebook.pdf](https://github.com/DevonDeRaad/SNPfiltR/files/8198316/R.Notebook.pdf)

**Comment by DevonDeRaad** [comment]
Hi, thanks for including your markdown documenting the code that you ran. From looking at your code, the error message "NaN% of het genotypes (NaN% of all genotypes)" indicates to me that the function filter_allele_balance() is not correctly recognizing the dimensions of the genotype matrix in your input vcf file. Your code looks good, so this is likely an internal bug related to the sometimes idiosyncratic formatting of vcf files generated by different programs. Is there any way you could provide me with the input file that causes this error so that I can recreate it for myself and make a bug fix to the package? Feel free to contact me directly at: devonderaad@gmail.com

Thanks!
Devon

**Comment by DevonDeRaad** [comment]
Hi, I was actually able to recreate these issues using the dDocent generated example vcf files that are publicly available as part of this tutorial (https://github.com/jpuritz/dDocent/blob/master/tutorials/Filtering%20Tutorial.md). I realized that dDocent doesn't automatically encode genotype quality or allele depth into output vcf files (which is fine, it just means that you can't perform filters requiring those fields). I have now updated the code in the functions 'filter_allele_balance', 'hard_filter', and 'max_depth', which require some type of genotype metadata information, so that they fail gracefully and throw an informative error message if they are used with an input vcf file lacking the requisite metadata info. As a note, you can still use hard_filter() to filter and visualize depth even if there is no genotype quality info (or vice versa). You should be able to download the current development version (which includes these updates) directly from GitHub, and these fixes will be included in the next CRAN release of the package. Thanks for your helpful feedback, this has made the package more broadly usable across vcf input formats!

**Comment by rspfau** [comment]
Thanks! Greatly appreciated!
